parameters:
#    daenoor_jobeet.example.class: Daenoor\JobeetBundle\Example

services:
#    daenoor_jobeet.example:
#        class: %daenoor_jobeet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
